config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'

  resources :products, only: [:index, :show] do
    post '/add_to_basket', to: 'products#add_to_basket'
    get '/remove_from_basket', to: 'products#remove_from_basket'
  end
  get '/basket', to: 'products#basket'
  post '/filter', to: 'products#filter'

  get '/checkout', to: 'checkouts#start'
  post '/checkout', to: 'checkouts#create'
  get '/finish', to: 'checkouts#finish'
  post "/hook" => "checkouts#hook"

  get '/home', to: 'static_pages#home'

  get '/about', to: 'static_pages#about'

  get '/contact', to: 'static_pages#contact'

  post '/contact/send', to: 'static_pages#send_contact_mail'

end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  name        :string
#  price       :decimal(, )
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category_id :integer
#  description :text
#  url         :string
#

class Product < ActiveRecord::Base
  belongs_to :category

  delegate :name, to: :category, prefix: true
  attr_accessor :amount

  scope :with_category_id, -> (category_id) { where(category_id: category_id) }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @category_id = params[:category][:category_id] unless params[:category].blank?
    @products = Product.all
    @products = @products.with_category_id(@category_id) unless @category_id.blank?
    @products = @products.paginate(page: params[:page], per_page: 20)
    @categories = Category.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_to_basket
    @product = Product.find(params[:product_id])
    amount = params[:product][:amount].to_i
    session[:basket] ||= []
    unless amount.blank? || amount == 0
      session[:basket].delete_if {|hash| hash["id"] == params[:product_id].to_i }
      session[:basket] << {id: @product.id, amount: amount} unless session[:basket].include? @product.id
      flash[:notice] = "Product added to your basket"
    else
      flash[:error] = "No amount selected"
    end
    redirect_to :back
  end

  def remove_from_basket
    session[:basket].delete_if {|hash| hash["id"] == params[:product_id].to_i } unless session[:basket].blank?
    redirect_to :basket
  end

  def basket
    @products = []
    unless session[:basket].blank?
      session[:basket].each do |p|
        product = Product.find(p["id"])
        product.amount = p["amount"].to_i
        @products << product
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/basket.html.slim
- total = 0
.row
  .panel.panel-default
    .panel-heading Basket
    .panel-body
      - if @products.count > 0
        - @products.each do |product|
          .col-sm-4.col-md-3
            .panel.panel-primary.thumbnail
              = image_tag product.url, size: '242x200'
              .caption
                - total += (product.price * product.amount)
                h3
                  = product.name
                p
                  |Price: 
                  = product.price
                  | &nbsp;$
                p
                  |Amount: 
                  = product.amount
                p
                  |Total: 
                  = (product.price * product.amount)
                  | &nbsp;$
                p
                  = link_to "Info", product, class: "btn btn-primary"
                  | &nbsp;
                  = link_to "Remove", product_remove_from_basket_path(product), class: "btn btn-danger"
        .col-xs-12.text-right
          | Total:
          strong = total
          | &nbsp;$
      - else
        h3 There is nothing in your basket!
.row.text-center
  - if @products.count > 0
    = link_to "Proceed to checkout", checkout_path, class: "btn btn-primary"

app/views/products/index.html.slim
.row
  .panel.panel-default
    .panel-heading Gallery
    .panel-body
      = simple_form_for :category, url: products_path, :method => :get do |f|
        .col-xs-12
          = f.label "Catergories:", required: false
        .col-xs-6
          = f.input :category_id, collection: @categories.pluck(:name, :id), selected: @category_id, label: false, include_blank: "All"
        = f.submit "Filter", class: 'btn btn-primary'
      br
      - @products.each do |product|
        = simple_form_for :product, url: product_add_to_basket_path(product), method: :post do |f|
          .col-sm-4.col-md-3
            .panel.panel-primary.thumbnail
              = image_tag product.url, size: '242x200'
              .caption
                h3= product.name
                p
                  = product.price
                  | &nbsp;$
                p
                  = product.description[0..200]
                  = f.input :amount, input_html: { value: 1 }
                p
                  = link_to "Info", product, class: "btn btn-primary"
                  | &nbsp;
                  / = link_to "Add to basket", product_add_to_basket_path(product), class: "btn btn-warning"
                  = f.submit "Add to Basket", class: "btn btn-warning"
.row.text-center
  = will_paginate @products, renderer: BootstrapPagination::Rails

app/views/products/show.html.slim
.row
  .panel.panel-default
    .panel-heading 
      | Product: 
      = @product.name
    .panel-body
      .col-xs-12.col-md-3
          .panel.panel-primary.thumbnail
            = image_tag @product.url, size: '242x200'
      p.col-xs-12.col-md-9
        = @product.description
      p.col-xs-12
        | Price: 
        strong
          = @product.price
        |&nbsp;$
      .col-xs-12
        = link_to "Back to Gallery", products_path, class: "btn btn-primary"
        | &nbsp;
        = link_to "Add to basket", product_add_to_basket_path(@product), class: "btn btn-warning"